extends: [airbnb-base, plugin:prettier/recommended]
env:
  browser: true
  es2024: true
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  no-param-reassign: off
