# DO NOT use this file to configure cops. All cop configuration should be
# handled by standardrb (or standardrb plugins).
#
# This file exists so that tooling which can integrate with Rubocop, but not
# directly with standardrb, will produce the expected results.
inherit_gem:
  standard: config/base.yml
  standard-rails: config/base.yml
require:
  - rubocop-rails
